### ISSUE TITLE
Grammar of text in intro diagram

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#323] opened 2017-03-03 22:36 UTC
The new homepage (created in #142 and based on the design) currently states:

- Push to GitHub.
- Built automatically.
- Published in the Snap Store

I understand the intention here, that it's trying to say "When you push to GitHub, your snap will be automatically built and published to the snap store", but to me these seem like 3 steps that either the user or the system are following, and so it's rather jarring to see the mixed tenses here.

Also, our style guide states that list items (as I think these are) shouldn't have have full stops, and I'm not sure whether "Snap Store" should be capitalised, as "snap" generally isn't.

---

Copied from Trello card: https://trello.com/c/GFoR8zlT/151-grammar-of-text-in-intro-diagram
Labels:

**Comment by matthewpaulthomas** [comment] 2017-04-03 15:26
Duplicate of #144.

**Closed by matthewpaulthomas** 2017-04-03 15:26 UTC
