### ISSUE TITLE
[header] change wordmark logo in header to orange to pull it out

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#366] opened 2017-03-03 22:50 UTC
Short term fix. To be agreed with Evan before landing

---

Copied from Trello card: https://trello.com/c/iA8O6Te7/293-header-change-wordmark-logo-in-header-to-orange-to-pull-it-out
Labels: Blocked

**Comment by matthewpaulthomas** [comment] 2017-03-14 10:17
Duplicate of #256.

**Closed by matthewpaulthomas** 2017-03-14 10:17 UTC
Labels: Status: Blocked
