### ISSUE TITLE
Ensure the progress meter is sufficiently spaced from any element below

### ISSUE THREAD

**Issue by jamiedawsonyoung** [canonical-ols/build.snapcraft.io#608] opened 2017-04-07 14:48 UTC
We need to make sure that there's no confusion between the progress meter and any element underneath it. If anything gets too close to it then it's possible users will associate one of the steps of the progress meter with whatever is underneath.

**Comment by evandandrea** [comment] 2017-04-21 11:19
Duplicate of #223

**Closed by evandandrea** 2017-04-21 11:19 UTC
Labels: Duplicate
