### ISSUE TITLE
[dashboard] Spacing between user details, progress bar, first-time text, and main component

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#314] opened 2017-03-03 22:36 UTC
The progress bar and first-time text look too closely packed, but I'm not sure what the proper spacing should be. Can someone from design provide guidance?

---

Copied from Trello card: https://trello.com/c/vXhusZok/245-dashboard-spacing-between-user-details-progress-bar-first-time-text-and-main-component
Labels: design

**Comment by matthewpaulthomas** [comment] 2017-03-06 10:58
Duplicate of #223.

**Comment by cjwatson** [comment] 2017-03-06 12:38
Closing as duplicate of #223, as above.

**Closed by cjwatson** 2017-03-06 12:38 UTC
