### ISSUE TITLE
cross browser testing

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#346] opened 2017-03-03 22:46 UTC
---

Copied from Trello card: https://trello.com/c/TQa23imD/315-cross-browser-testing
Labels:

**Comment by matthewpaulthomas** [comment] 2017-03-27 14:37
Duplicate of #448 which has more discussion and is marked for Beta launch.

**Closed by matthewpaulthomas** 2017-03-27 14:37 UTC
