### ISSUE TITLE
Error importing .png file

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#267] opened 2017-03-03 22:04 UTC
---

Copied from Trello card: https://trello.com/c/ipOU5kvd/249-error-importing-png-file
Labels:

**Comment by katiefenn** [comment] 2017-03-07 11:21
K: 2,
B: 2,
C: 2

**Comment by matthewpaulthomas** [comment] 2017-03-27 14:41
Duplicate of #151.

**Closed by matthewpaulthomas** 2017-03-27 14:41 UTC
Labels: Type: Technical debt
