### ISSUE TITLE
[dashboard] Better distinguish interactive table rows

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#326] opened 2017-03-03 22:45 UTC
Need to show on a table: 

- Collapsed row
- Expanded row
- Selected cell

(try without a grey block background)

---

Copied from Trello card: https://trello.com/c/WehUCR4V/301-dashboard-better-distinguish-interactive-table-rows
Labels: design

**Comment by matthewpaulthomas** [comment] 2017-04-28 14:08
Duplicate of #321.

**Closed by matthewpaulthomas** 2017-04-28 14:08 UTC
Labels: Status: Triaged
