### ISSUE TITLE
install instructions to test the snap appear before the snap is in the store

### ISSUE THREAD

**Issue by elopio** [canonical-ols/build.snapcraft.io#718] opened 2017-05-05 00:12 UTC
I'm building a new snap, and it shows the text:

> To test this snap on your PC or cloud instance:
> 
> sudo snap install --edge dillinger-elopio 

The problem is that the snap is not yet in the store, so if I run those commands they will fail. This text should be visible only after the snap has been built and published to edge.

![selection_004](https://cloud.githubusercontent.com/assets/617831/25729822/2d5a6004-30f5-11e7-9b79-bb3b9aff6bca.png)

**Comment by evandandrea** [comment] 2017-05-05 00:37
Duplicate of #528

**Closed by evandandrea** 2017-05-05 00:37 UTC

**Comment by elopio** [comment] 2017-05-05 00:55
Oh, already fixed. Magic! thanks.

**Comment by evandandrea** [comment] 2017-05-05 01:13
On staging 😄
