### ISSUE TITLE
Organisations: Only show delete icon when the GitHub user owns the snap

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#649] opened 2017-04-21 09:37 UTC
This probably requires persisting some data about which actions were performed by which GitHub users.

**Comment by evandandrea** [comment] 2017-04-21 11:20
@nottrobin is this a duplicate of #646?

**Comment by magdalena-mirowicz** [comment] 2017-04-25 11:17
duplicate of #646

**Closed by magdalena-mirowicz** 2017-04-25 11:17 UTC
Labels: Status: Design required, Status: Triaged
