### ISSUE TITLE
"Add repos" list: Avoid pagination

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#659] opened 2017-04-21 13:06 UTC
We discussed alternatives to pagination in the workshop, and decided that we should explore a solution similar to:

- Make the "Add" button sticky, either at the top of the bottom of the screen
- Explore either infinite scrolling functionality or using a "Load more" button

This may also be partially solved or complemented by https://github.com/canonical-ols/build.snapcraft.io/issues/330

**Comment by nottrobin** [comment] 2017-04-21 13:15
This may also effect whether #379 is necessary

**Comment by matthewpaulthomas** [comment] 2017-04-28 09:21
This issue is a bit confused: whether we have pagination is completely independent of whether the “Add” button is always visible. It should be always visible, but even if it was, the list might still be paginated.

Either way, it’s a duplicate. If it’s about getting rid of pagination, it’s a duplicate of #383. And if it’s about making sure the “Add” button is always visible, it’s effectively a duplicate of #564 (since it has exactly the same solution).

**Closed by matthewpaulthomas** 2017-04-28 09:21 UTC
Labels: Design: Required, Status: Triaged
