### ISSUE TITLE
Dashboard does not update when GitHub repo changes

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#399] opened 2017-03-06 12:33 UTC
https://zapier.com/engine/hydrate/54157/.eJwVjEEOgyAUBe_y1i4EoVAO0SuQL3wrodJGSBpjvHvpdmYyJ1KpjUpgnyKcuKubkEoNWBK_oi-0MRyoNQrrxqVVDAgrh-wzH3BaCW06eZfWpW_H558_epS_tD8r3IlAez9D25l4JBNZznaRZpLRTqOWuK4fS-sp7A:1ckrpQ:f6df3u9VT-1xjJ_IGN4GuCAFcVU/

Comments:

**Steps to reproduce:**

1. Register a name different from what is in the snapcraft.yaml
1. In a new tab, go to GitHub and edit the snapcraft.yaml to match the registered name

**What happens:**

* The original tab is not updated: the table still says the names do not match

**What should happen:**

* The table automatically refreshes to show the mismatched name issue resolved 

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/e9FDGou5/339-dashboard-does-not-update-when-github-repo-changes
Labels: copy to github

**Comment by matthewpaulthomas** [comment] 2017-03-09 11:52
Duplicate of #397.

**Closed by matthewpaulthomas** 2017-03-09 11:52 UTC
Labels: Type: Bug
