### ISSUE TITLE
"Get started with a template" link assumes my branch is called "master" without checking

### ISSUE THREAD

**Issue by stuartlangridge** [canonical-ols/build.snapcraft.io#611] opened 2017-04-10 10:39 UTC
Attempting to use b.s.io to package my ColourPicker project at https://github.com/stuartlangridge/ColourPicker/, I get a link to "get started with a template". This link goes to

https://github.com/stuartlangridge/ColourPicker/new/master?filename=snap%2Fsnapcraft.yaml&value=%0Aname%3A%20my-snap-name%20%23%20you%20probably%20want%20to%20%27snapcraft%20register%20%3Cname%3E%27%0Aversion%3A%20%270.1%27%20%23%20just%20for%20humans%2C%20typically%20%271.2%2Bgit%27%20or%20%271.3.2%27%0Asummary%3A%20Single-line%20elevator%20pitch%20for%20your%20amazing%20snap%20%23%2079%20char%20long%20summary%0Adescription%3A%20%7C%0A%20%20This%20is%20my-snap%27s%20description.%20You%20have%20a%20paragraph%20or%20two%20to%20tell%20the%0A%20%20most%20important%20story%20about%20your%20snap.%20Keep%20it%20under%20100%20words%20though%2C%0A%20%20we%20live%20in%20tweetspace%20and%20your%20description%20wants%20to%20look%20good%20in%20the%20snap%0A%20%20store.%0A%0Agrade%3A%20devel%20%23%20must%20be%20%27stable%27%20to%20release%20into%20candidate%2Fstable%20channels%0Aconfinement%3A%20devmode%20%23%20use%20%27strict%27%20once%20you%20have%20the%20right%20plugs%20and%20slots%0A%0Aparts%3A%0A%20%20my-part%3A%0A%20%20%20%20%23%20See%20%27snapcraft%20plugins%27%0A%20%20%20%20plugin%3A%20nil%0A

which is a 404. This is, I suspect, because ColourPicker has its main branch named "app", not "master", and b.s.io doesn't check and just hardcodes "master". Which is of course rather naughty. :)

**Comment by cjwatson** [comment] 2017-04-10 10:43
Indeed.  Duplicate of #497, though.

**Closed by cjwatson** 2017-04-10 10:43 UTC
