### ISSUE TITLE
"Add repos": Add empty state [3]

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#658] opened 2017-04-21 13:01 UTC
The message that is shown when you try to add a new GitHub repository but you don't have any:

![no repos](https://assets.ubuntu.com/v1/8979a609-no-repos.png)

Needs updating to accommodate organisation support.

**Comment by evandandrea** [comment] 2017-04-22 19:05
Given that the empty state for "add repos" isn't implemented at all yet and there's no issue to track it, can I suggest we retitle this to "Add repos empty state" and point it at [the spec](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.43owh6tjv12q)?

**Comment by nottrobin** [comment] 2017-04-24 10:14
@evandandrea done.

**Comment by matthewpaulthomas** [comment] 2017-04-24 14:15
The spec already describes the empty state in detail, so this does not require any design.

Further, the empty-state text varies depending on whether adding organization repos has been implemented yet. If this will land before that, then the fix for #621 should include updating the text accordingly.

**Comment by nottrobin** [comment] 2017-04-24 15:51
@matthewpaulthomas I don't see how this is related to #621 - as far as I understood that is a completely behind-the-scenes piece of work that doesn't effect the user interface at all. @cjwatson correct me if I'm wrong.

**Comment by cjwatson** [comment] 2017-04-24 17:20
@nottrobin That's correct, #621 is entirely behind-the-scenes.  Perhaps @matthewpaulthomas typoed the issue number?

**Comment by matthewpaulthomas** [comment] 2017-04-25 12:28
Duplicate of #422.

**Closed by matthewpaulthomas** 2017-04-25 12:28 UTC
Labels: Design: Required, Status: Triaged
