### ISSUE TITLE
isFetching

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#279] opened 2017-03-03 22:04 UTC
See: https://github.com/canonical-ols/build.snapcraft.io/pull/236#pullrequestreview-24026052

---

Copied from Trello card: https://trello.com/c/j4djE7XT/292-isfetching
Labels:

**Comment by katiefenn** [comment] 2017-03-07 10:43
Deferred for further discussion

**Comment by bartaz** [comment] 2017-04-12 10:43
Duplicate of #625

**Closed by bartaz** 2017-04-12 10:43 UTC
Labels: Type: Question, Type: Technical debt
