### ISSUE TITLE
Organisations: Go straight to "My repos" dashboard on login if any of your org repos have been setup by other people

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#645] opened 2017-04-21 09:08 UTC
Change the logic around first login - so that people are shown the dashboard if any organisation repos have been setup.

**Comment by matthewpaulthomas** [comment] 2017-04-24 14:24
Duplicate of (the newer but clearer) #665.

**Closed by matthewpaulthomas** 2017-04-24 14:24 UTC
Labels: Confirmed
