### ISSUE TITLE
[Request] Add option to choose the github branch to use

### ISSUE THREAD

**Issue by theshadowx** [canonical-ols/build.snapcraft.io#701] opened 2017-04-30 10:59 UTC
From the code : 
https://github.com/canonical-ols/build.snapcraft.io/blob/master/src/server/handlers/launchpad.js#L273

```
  logger.info(`Creating new snap for ${repositoryUrl}`);
  return lpClient.named_post('/+snaps', 'new', {
    parameters: {
      owner: `/~${username}`,
      distro_series: `/${DISTRIBUTION}/${DISTRO_SERIES}`,
      name: `${makeSnapName(repositoryUrl)}-${DISTRO_SERIES}`,
      git_repository_url: repositoryUrl,
      git_path: 'refs/heads/master',
      // auto_build will be enabled later, once snapcraft.yaml exists and
      // the snap name has been registered.
      auto_build: false,
      auto_build_archive: `/${DISTRIBUTION}/+archive/primary`,
      auto_build_pocket: 'Updates',
      processors: ARCHITECTURES.map((arch) => `/+processors/${arch}`)
    }
  });
```

It fetches automatically the master branch, is it possible to use the default branch set in github or to add option to choose from which branch to build the snap.

Thanks

**Comment by cjwatson** [comment] 2017-04-30 12:19
Duplicate of #440 / #497.

**Closed by cjwatson** 2017-04-30 12:19 UTC
