### ISSUE TITLE
[Dashboard] Don't give user a link to the build detail page until there is a log for them to see

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#357] opened 2017-03-03 22:47 UTC
---

Copied from Trello card: https://trello.com/c/PcB85s59/231-dashboard-don-t-give-user-a-link-to-the-build-detail-page-until-there-is-a-log-for-them-to-see
Labels:

**Comment by matthewpaulthomas** [comment] 2017-03-08 09:05
In Trello, I wrote:
> The actual problem is: it’s possible to get to a build page with an empty “Build log” box.
>
> Removing the link to the page would greatly reduce the number of people who see the problem, though it wouldn’t actually fix the problem. The URL of the page is easy to guess.
>
> Removing the link would also stymie the use case of opening the build page for a queued build, then glancing at it occasionally (on a secondary display, or while doing housework) to check on its status.
>
> A simpler and more forward-compatible solution would be to place a spinner, or status text, or both, inside the build log box until text appears in it.

**Comment by bartaz** [comment] 2017-03-08 09:38
Seems to be duplicate of #416 that was just finished and merged.

I agree that hiding the link is rather workaround then solution.

Currently build details page shows text "The build log will appear here once the build has finished." instead of the box if log is not yet available.

Ideally when we have better support for showing partial log from LP we could revert back and show links to even uncompleted builds.

**Comment by magdalena-mirowicz** [comment] 2017-03-10 11:34
@bartaz should this be closed?

**Comment by matthewpaulthomas** [comment] 2017-03-13 17:26
For the reasons given above, I’m not changing the spec to include this. If it has already been done (for example, if it really is a duplicate of #416), that’s no big deal, but it should be undone once partial logs are implemented (#295).

**Closed by matthewpaulthomas** 2017-03-13 17:26 UTC
Labels: Status: Design required, Status: Proposal, Type: Question
