### ISSUE TITLE
The name registration text entry is too small (short) for tall text to be read properly

### ISSUE THREAD

**Issue by nataliabidart** [canonical-ols/build.snapcraft.io#631] opened 2017-04-12 15:13 UTC
I have a repo called "yes" and the y in the yes is not shown completely in the name registration text entry. It's read as "ves" which was confusing because I thought it was suggesting me to register "ves" instead of "yes".

**Comment by matthewpaulthomas** [comment] 2017-04-12 15:35
Duplicate of #539.

**Closed by matthewpaulthomas** 2017-04-12 15:35 UTC
