### ISSUE TITLE
More padding on "let's check out your repos"

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#403] opened 2017-03-06 12:33 UTC
"Let's check out your repos" sits right under "built automatically". Could we give it more room?

https://zapier.com/engine/hydrate/54157/.eJwVjEkOwjAMAP_icy-B7I_gC5HjGBqFBtRaqqqqfydcZ0ZzQu2bYCdOtUBUQVt103qCZ-V3SR0XhggogjQv3GWDCWhmaqnxAdFoZdwgny5DJjm-__wxorbj-tognkC4jjMYn11RJYRMnu5ovcreahfgun5IGynY:1ckrpY:44qGdpFZR_XY3JIp5GYQpzxblOA/

Comments:

Can we use the same top margin as the button so the text doesn't jump up too. `margin-top: 2.4em`

---
Creator: Robin Winslow
Assignees: 
Copied from Trello card: https://trello.com/c/VR93kpGM/319-more-padding-on-let-s-check-out-your-repos
Labels: copy to github

**Comment by evandandrea** [comment] 2017-04-21 11:17
Duplicate of #568

**Closed by evandandrea** 2017-04-21 11:17 UTC
Labels: Duplicate
