### ISSUE TITLE
Renaming a snap to trigger "doesn't match" then refreshing page drops text

### ISSUE THREAD

**Issue by evandandrea** [canonical-ols/build.snapcraft.io#711] opened 2017-05-03 19:58 UTC
<img width="1125" alt="screen shot 2017-05-03 at 15 49 32" src="https://cloud.githubusercontent.com/assets/1523179/25678585/312dc708-3018-11e7-88d0-a380a5f2a486.png">

If you rename a snap so the snapcraft.yaml no longer matches, "doesn't match" appears in the configured cell. Clicking on "doesn't match" expands to:

> The snapcraft.yaml uses the snap name “awscli”, but you’ve registered the name “awscli-ev”.

Could this also include the links to:

> Change snapcraft.yaml to use “{name}”
> Register the name “{name in snapcraft.yaml}”

**Comment by matthewpaulthomas** [comment] 2017-05-04 09:18
Duplicate of #705.

**Closed by matthewpaulthomas** 2017-05-04 09:18 UTC
