### ISSUE TITLE
Removing the snapcraft.yaml does not reset the "configured" state

### ISSUE THREAD

**Issue by nottrobin** [canonical-ols/build.snapcraft.io#291] opened 2017-03-03 22:35 UTC
---

Copied from Trello card: https://trello.com/c/9vynWiki/330-bug-removing-the-snapcraft-yaml-does-not-reset-the-configured-state
Labels: Bug

**Comment by pmahnke** [comment] 2017-03-06 15:12
To reproduce:

* Add a repo with a snapcraft.yaml to the dashboard
* Remove the snapcraft.yaml on GitHub
* Refresh the page

What happens:

* The repo still shows as configured
* What should happen:

The repo shows as unconfigured

**Comment by matthewpaulthomas** [comment] 2017-03-07 10:04
Duplicate of #293.

**Closed by matthewpaulthomas** 2017-03-07 10:04 UTC
Labels: Status: Next, Type: Bug
